version: "3"
services:
  node:
    image: "parcel-starter"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:1234"
      - "38833:38833"
    command: yarn start --hmr-port 38833